server:
  port: 8081

spring:
#  jackson:
#  date-format: yyyy-MM-dd'T'HH:mm:ssZ
  time-zone: Europe/Zagreb
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
  task:
    scheduling:
      pool:
        size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/rkyv_system_db?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connectionTimeout: 30000
#      idleTimeout: 600000
#      maxLifetime: 1800000

springdoc:
  api-docs:
    path: /cfe-api-docs # http://localhost:8080/v3/cfe-api-docs/
  swagger-ui:
    path: /cfe-swagger-ui.html # http://localhost:8080/cfe-swagger-ui.html
    operationsSorter: method

chat-server:
  timeToLive: 5
  messageHistoryDays: 7

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: ERROR
    com:
      cfe:
        chat: DEBUG
cron:
  expression:
    user: 0 0 0 * * *
    group: 0 0 0 * * *